### ISSUE TITLE
salt-lint fails to install in our CI (gitlab-ci) on docker/k8/python3.8

### ISSUE THREAD

**Issue by arthurlogilab** [warpnet/salt-lint#107]
```
salt-lint installdeps: salt-lint
ERROR: invocation failed (exit code 1), logfile: /project/salt/.tox/salt-lint/log/salt-lint-1.log
================================== log start ===================================
Collecting salt-lint
  Downloading https://files.pythonhosted.org/packages/b0/b9/ac19b85dee7a8a34778ade04026a7e4bbd1378248d94285813c53f814223/salt-lint-0.1.0.tar.gz
Collecting salt
  Downloading https://files.pythonhosted.org/packages/a3/99/b3e5c77b8383fdd04fce0161c2ee58a21633a37b3b8d8367d6449023eb8c/salt-2019.2.2.tar.gz (14.4MB)
    ERROR: Command errored out with exit status 1:
     command: /project/salt/.tox/salt-lint/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ep648kpl/salt/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ep648kpl/salt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-ep648kpl/salt/pip-egg-info
         cwd: /tmp/pip-install-ep648kpl/salt/
    Complete output (14 lines):
    Traceback (most recent call last):
      File "/tmp/pip-install-ep648kpl/salt/salt/version.py", line 15, in <module>
        from platform import linux_distribution as _deprecated_linux_distribution
    ImportError: cannot import name 'linux_distribution' from 'platform' (/usr/local/lib/python3.8/platform.py)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ep648kpl/salt/setup.py", line 137, in <module>
        exec(compile(open(SALT_VERSION).read(), SALT_VERSION, 'exec'))
      File "/tmp/pip-install-ep648kpl/salt/salt/version.py", line 22, in <module>
        from distro import linux_distribution
    ModuleNotFoundError: No module named 'distro'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by roaldnefs** [comment]
Thanks @arthurlogilab for your bug report! This is due to a missing dependency in salt itself (_which is a dependency of `salt-lint`_), for more information see: https://github.com/saltstack/salt/issues/55029.

**Comment by roaldnefs** [comment]
A simple temporary fix might be to install `distro` before installing `salt-lint` using:

```console
$ pip install distro
$ pip install salt-lint
```
Installing them in one line might still result in the same error as the build order might be different. As this is an open issue on the SaltStack side, I will close this issue.
