### ISSUE TITLE
Permission error on temporary file

### ISSUE THREAD

**Issue by amendlik** [warpnet/salt-lint#262]
**Describe the bug**
Permission error when processing STDIN on Windows.

```
Traceback (most recent call last):
  File "c:\users\amendlik\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\amendlik\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\amendlik\AppData\Local\Programs\Python\Python38\Scripts\salt-lint.exe\__main__.py", line 7, in <module>
  File "c:\users\amendlik\appdata\local\programs\python\python38\lib\site-packages\saltlint\cli.py", line 72, in run
    os.unlink(stdin_file.name)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\amendlik\\AppData\\Local\\Temp\\tmp8xwwjien.sls'
```

**To Reproduce**

1. From the Windows command line
2. Execute `salt-lint` with input from STDIN, such as:
```
type states\wordpress\init.sls | C:\Users\amendlik\AppData\Local\Programs\Python\Python38\Scripts\salt-lint.exe
```

**Expected behavior**
File should be processed the same as if it the file name was passed as an argument, such as:
```
C:\Users\amendlik\AppData\Local\Programs\Python\Python38\Scripts\salt-lint.exe states\wordpress\init.sls
[207] File modes should always be encapsulated in quotation marks
states\wordpress\init.sls:38
    - mode: 644

[208] File modes should always contain a leading zero
states\wordpress\init.sls:38
    - mode: 644
```

**Desktop (please complete the following information):**

- OS: Windows
- Version 10

**Additional context**
The Sublime Text linter plugin invokes `salt-lint` by passing data to STDIN. Please see the issue attached to that project: warpnet/SublimeLinter-salt-lint#19

**Comment by roaldnefs** [comment]
This has been fixed in PR #263 which was included in salt-lint version `v0.7.0` (_released 6 days ago_).
